# Generated by Django 3.2.4 on 2021-06-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Shoubhit', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(default='22 May 2021', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='Django, Wordpress, Bootstrap', max_length=40),
        ),
    ]
