# Generated by Django 3.2.4 on 2021-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210625_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default='Jun 27, 2021', max_length=30),
        ),
    ]
